
development:
  
  adapter: postgresql
  database: graficaandrade_development
  username: postgres
  password: 
  host: localhost
  encoding: UTF8
  collate: pt_BR.UTF8
  ctype: pt_BR.UTF8
  template: template0
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: graficaandrade_test
  username: postgres
  password: 
  host: localhost
  encoding: UTF8
  collate: pt_BR.UTF8
  ctype: pt_BR.UTF8
  template: template0
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: graficaandrade_production
  username: postgres
  password: 
  host: localhost
  encoding: UTF8
  collate: pt_BR.UTF8
  ctype: pt_BR.UTF8
  template: template0
  pool: 5
  timeout: 5000
